namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum AffixSpanEquipmentToParentErrorCodes
    {
        INVALID_ROUTE_NODE_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_SEGMENT_ID_CANNOT_BE_EMPTY,
        ERROR_TRACING_SPAN_SEGMENT,
        INVALID_SPAN_SEGMENT_ID,
        NEW_UTILITY_NETWORK_HOP_IS_NOT_VALID,
        INVALID_SPAN_SEGMENT_ID_NOT_FOUND,
        NO_CABLE_SPAN_SEGMENT_NOT_FOUND,
        NO_CONDUIT_SPAN_SEGMENT_NOT_FOUND,
        NON_MULTI_LEVEL_CONDUIT_CANNOT_CONTAIN_MORE_THAN_ONE_CABLE,
        CONDUIT_SEGMENT_ALREADY_CONTAIN_CABLE
    }
}
