namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum ConnectSpanEquipmentAndTerminalEquipmentErrorCodes
    {
        INVALID_ROUTE_NODE_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_SEGMENT_LIST_CANNOT_BE_EMPTY,
        SPAN_SEGMENT_NOT_FOUND,
        INVALID_TERMINAL_LIST_CANNOT_BE_EMPTY,
        INVALID_SPAN_SEGMENT_LIST_AMOUNT_MUST_BE_EQUAL_TERMINAL_LIST_AMOUNT,
        TERMINAL_NOT_FOUND,
        INVALID_CONNECTS_LIST_CANNOT_BE_EMPTY,
        TERMINAL_ALREADY_CONNECTED,
    }
}
