namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum CutSpanSegmentsAtRouteNodeErrorCodes
    {
        SPAN_EQUIPMENT_AND_ROUTE_NODE_WHERE_TO_CUT_IS_NOT_COLOCATED,
        INVALID_ROUTE_NODE_ID_CANNOT_BE_EMPTY,
        OUTER_SPAN_IS_NOT_CUT,
        INVALID_SPAN_SEGMENT_LIST_CANNOT_BE_EMPTY,
        SPAN_SEGMENT_ALREADY_CUT,
        SPAN_SEGMENT_NOT_FOUND,
        SPAN_EQUIPMENT_CANNOT_BE_CUT_AT_ENDS,
        FAILED_TO_GET_SPAN_EQUIPMENT_WALK_OF_INTEREST_INFORMATION,
        SPAN_EQUIPMENT_NOT_AFFIXED_TO_NODE_CONTAINER,
        SPAN_SEGMENT_CONTAIN_CABLE
    }
}
