namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum DetachSpanEquipmentFromNodeContainerErrorCodes
    {
        INVALID_NODE_CONTAINER_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_SEGMENT_ID_CANNOT_BE_EMPTY,
        INVALID_NODE_CONTAINER_ID_NOT_FOUND,
        INVALID_SPAN_EQUIPMENT_OR_SEGMENT_ID_NOT_FOUND,
        SPAN_EQUIPMENT_IS_NOT_AFFIXED_TO_NODE_CONTAINER,
        SPAN_SEGMENT_IS_CONNECTED_INSIDE_NODE_CONTAINER,
        SPAN_SEGMENT_IS_CUT_INSIDE_NODE_CONTAINER,
        SPAN_EQUIPMENT_IS_NOT_AFFIXED_TO_PARENTS_IN_NODE
    }
}
