namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum DisconnectSpanSegmentsAtRouteNodeErrorCodes
    {
        INVALID_ROUTE_NODE_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_SEGMENT_LIST_CANNOT_BE_EMPTY,
        SPAN_SEGMENT_NOT_FOUND,
        SPAN_EQUIPMENT_AND_ROUTE_NODE_WHERE_TO_CONNECT_IS_NOT_COLOCATED,
        SPAN_SEGMENTS_ARE_NOT_CONNECTED,
        EXPECTED_A_SPAN_SEGMENT_FROM_TWO_SPAN_EQUIPMENT,
        INVALID_SPAN_SEGMENT_LIST_MUST_CONTAIN_TWO_SPAN_SEGMENT_IDS,
        SPAN_SEGMENT_IS_NOT_RELATED_TO_ROUTE_NODE,
        SPAN_SEGMENT_NOT_CONNECTED_TO_TERMINAL,
        CANNOT_CONNECT_SPAN_EQUIPMENT_TO_ITSELF,
        CANNOT_DISCONNECT_SPAN_SEGMENT_TO_ITSELF,
        INVALID_SPAN_DISCONNECT_LIST_CANNOT_BE_EMPTY,
        CONNECTED_TERMINAL_NOT_FOUND
    }
}
