namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum PlaceAdditionalStructuresInSpanEquipmentErrorCodes
    {
        INVALID_SPAN_EQUIPMENT_ID_CANNOT_BE_EMPTY,
        INVALID_STRUCTURE_SPECIFICAION_ID_LIST_CANNOT_BE_EMPTY,
        INVALID_STRUCTURE_SPECIFICATION_ID_NOT_FOUND,
        INVALID_SPAN_EQUIPMENT_ID_NOT_FOUND,
        CANNOT_ADD_SPAN_STRUCTURES_TO_FIXED_SPAN_EQUIPMENT
    }
}
