namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum PlaceSpanEquipmentInRouteNetworkErrorCodes
    {
        INVALID_SPAN_EQUIPMENT_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_EQUIPMENT_SPECIFICATION_ID_NOT_FOUND,
        INVALID_INTEREST_KIND_MUST_BE_WALK_OF_INTEREST,
        INVALID_SPAN_EQUIPMENT_ALREADY_EXISTS,
        INVALID_UTILITY_NETWORK_HOP_LIST_CANNOT_BE_EMPTY,
        INVALID_WALK_MUST_CONTAIN_AT_LEAST_THREE_ELEMENTS
    }
}
