namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum RemoveSpanStructureFromSpanEquipmentErrorCodes
    {
        SPAN_SEGMENT_NOT_FOUND,
        CANNOT_REMOVE_SPAN_STRUCTURES_FROM_FIXED_SPAN_EQUIPMENT,
        CANNOT_REMOVE_SPAN_STRUCTURE_WITH_CONNECTED_SEGMENTS_FROM_SPAN_EQUIPMENT,
        CANNOT_REMOVE_SPAN_EQUIPMENT_WITH_CONNECTED_SEGMENTS,
        SPAN_SEGMENT_CONTAIN_CABLE
    }
}
