namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum RemoveNodeContainerFromRouteNetworkErrorCodes
    {
        NODE_CONTAINER_NOT_FOUND,
        CANNOT_REMOVE_NODE_CONTAINER_WITH_AFFIXED_SPAN_EQUIPMENT,
        CANNOT_REMOVE_NODE_CONTAINER_CONTAINING_RACKS,
        CANNOT_REMOVE_NODE_CONTAINER_CONTAINING_TERMINAL_EQUIPMENT
    }
}
