namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum UpdateEquipmentPropertiesErrorCodes
    {
        NO_CHANGE_TO_MARKING_INFO,
        NO_CHANGE,
        NO_CHANGE_TO_MANUFACTURER,
        NO_CHANGE_TO_SPECIFICATION,
        CANNOT_CHANGE_FROM_NON_FIXED_TO_FIXED,
        CANNOT_REMOVE_SPAN_STRUCTURE_WITH_CONNECTED_SEGMENTS_FROM_SPAN_EQUIPMENT,
        SPAN_EQUIPMENT_NOT_FOUND,
        SPAN_SPECIFICATION_NOT_FOUND,
        NO_CHANGE_TO_ADDRESS_INFO,
        TERMINAL_EQUIPMENT_NOT_FOUND,
        NODE_CONTAINER_NOT_FOUND,
        NO_CHANGE_TO_NAMING_INFO,
        TERMINAL_STRUCTURE_NOT_FOUND
    }
}
