namespace OpenFTTH.RouteNetwork.API.Commands
{
    public enum RegisterWalkOfInterestErrorCodes
    {
        UNHANDLED_EXCEPTION,
        INVALID_INTEREST_KIND_MUST_BE_WALK_OF_INTEREST,
        INVALID_INTEREST_ID_CANNOT_BE_EMPTY,
        INVALID_INTEREST_ALREADY_EXISTS,
        INVALID_WALK_CANNOT_BE_EMPTY,
        INVALID_WALK_SHOULD_CONTAIN_ROUTE_SEGMENT_IDS_ONLY,
        INVALID_WALK_SEGMENTS_ARE_NOT_ADJACENT,
        INVALID_WALK_CANNOT_FIND_ROUTE_NETWORK_ELEMENT,
        INVALID_INTEREST_DONT_EXISTS,
        INVALID_WALK_ROUTE_NETWORK_ELEMENTS_ARE_NOT_ADJACENT,
        INVALID_WALK_ADJACENT_ROUTE_NETWORK_ELEMENTS_ARE_OF_SAME_TYPE,
        INVALID_WALK_FIRST_ROUTE_NETWORK_ELEMENT_MUST_BE_A_NODE,
        INVALID_WALK_LAST_ROUTE_NETWORK_ELEMENT_MUST_BE_A_NODE
    }
}
